/*
 * BouncerAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BouncerAPI.Standard;
using BouncerAPI.Standard.Utilities;

namespace BouncerAPI.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum ListEnum
    {
        WHITELIST, //TODO: Write general description for this method
        BLACKLIST, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type ListEnum
    /// </summary>
    public static class ListEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "Whitelist", "Blacklist" };

        /// <summary>
        /// Converts a ListEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The ListEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(ListEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case ListEnum.WHITELIST:
                case ListEnum.BLACKLIST:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of ListEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of ListEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<ListEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into ListEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed ListEnum value</returns>
        public static ListEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type ListEnum", value));

            return (ListEnum) index;
        }
    }
} 