/*
 * BouncerAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BouncerAPI.Standard;
using BouncerAPI.Standard.Utilities;


namespace BouncerAPI.Standard.Models
{
    public class LoginToBouncerAPIResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string accessToken;
        private string tokenType;
        private string expiresIn;
        private string claimLevel;

        /// <summary>
        /// the access token to use in all future requests
        /// </summary>
        [JsonProperty("access_token")]
        public string AccessToken 
        { 
            get 
            {
                return this.accessToken; 
            } 
            set 
            {
                this.accessToken = value;
                onPropertyChanged("AccessToken");
            }
        }

        /// <summary>
        /// always `bearer`
        /// </summary>
        [JsonProperty("token_type")]
        public string TokenType 
        { 
            get 
            {
                return this.tokenType; 
            } 
            set 
            {
                this.tokenType = value;
                onPropertyChanged("TokenType");
            }
        }

        /// <summary>
        /// the expiry of this bearer token in seconds
        /// </summary>
        [JsonProperty("expires_in")]
        public string ExpiresIn 
        { 
            get 
            {
                return this.expiresIn; 
            } 
            set 
            {
                this.expiresIn = value;
                onPropertyChanged("ExpiresIn");
            }
        }

        /// <summary>
        /// always `complete`
        /// </summary>
        [JsonProperty("claim_level")]
        public string ClaimLevel 
        { 
            get 
            {
                return this.claimLevel; 
            } 
            set 
            {
                this.claimLevel = value;
                onPropertyChanged("ClaimLevel");
            }
        }
    }
} 