/*
 * BouncerAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BouncerAPI.Standard;
using BouncerAPI.Standard.Utilities;


namespace BouncerAPI.Standard.Models
{
    public class SearchResult : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string inputIP;
        private List<Models.IPAddressEntryPair> entries;

        /// <summary>
        /// the input search string, with the proper '/' in CIDR, not '+' as needed in the endpoint URL
        /// </summary>
        [JsonProperty("Input_IP")]
        public string InputIP 
        { 
            get 
            {
                return this.inputIP; 
            } 
            set 
            {
                this.inputIP = value;
                onPropertyChanged("InputIP");
            }
        }

        /// <summary>
        /// matching IP Address and Object Entry IDs
        /// </summary>
        [JsonProperty("Entries")]
        public List<Models.IPAddressEntryPair> Entries 
        { 
            get 
            {
                return this.entries; 
            } 
            set 
            {
                this.entries = value;
                onPropertyChanged("Entries");
            }
        }
    }
} 