/*
 * BouncerAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BouncerAPI.Standard.Http.Client;

using BouncerAPI.Standard.Models;
using BouncerAPI.Standard;
using BouncerAPI.Standard.Utilities;


namespace BouncerAPI.Standard.Exceptions
{
    public class ReturnException : APIException 
    {
        // These fields hold the values for the public properties.
        private string status;
        private string error;

        /// <summary>
        /// The status of the return
        /// </summary>
        [JsonProperty("Status")]
        public string Status 
        { 
            get 
            {
                return this.status; 
            } 
            private set 
            {
                this.status = value;
            }
        }

        /// <summary>
        /// the error value
        /// </summary>
        [JsonProperty("Error")]
        public string Error 
        { 
            get 
            {
                return this.error; 
            } 
            private set 
            {
                this.error = value;
            }
        }

        /// <summary>
        /// Initialization constructor
        /// </summary>
        /// <param name="reason"> The reason for throwing exception </param>
        /// <param name="context"> The HTTP context that encapsulates request and response objects </param>
        public ReturnException(string reason, HttpContext context)
            : base(reason, context)
        {
        }
    }
} 