# -*- coding: utf-8 -*-

"""
    bouncerapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import jsonpickle
import dateutil.parser
from .controller_test_base import ControllerTestBase
from ..test_helper import TestHelper
from bouncerapi.api_helper import APIHelper


class CheckIPAddressesControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(CheckIPAddressesControllerTests, cls).setUpClass()
        cls.controller = cls.api_client.check_ip_addresses

    # Check if an IP Address is Already White- or Black-Listed
    def test_test_for_list_membership_1(self):
        # Parameters for the API call
        ip_address = '192.168.100.14'

        # Perform the API call through the SDK function
        result = self.controller.test_for_list_membership(ip_address)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = None

        self.assertTrue(TestHelper.match_headers(expected_headers, self.response_catcher.response.headers))

        
        # Test whether the captured response is as we expected
        self.assertIsNotNone(result)
        self.assertEqual('{  "Result": {    "List": "Whitelist",    "Status": "Success",    "Message": ""  },  "Entry": {    "IPv4": "192.168.100.14/24",    "IPv6": "2001:db8::/64",    "Start_Date": "2019-04-05T02:04:16Z",    "End_Date": "2019-04-05T02:04:16Z",    "Comments": "noteworthy note",    "Active": true  }}', self.response_catcher.response.raw_body)


