/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.controllers;

import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;

import com.example.www.*;
import com.example.www.models.*;
import com.example.www.exceptions.*;
import com.example.www.http.client.HttpClient;
import com.example.www.http.client.HttpContext;
import com.example.www.http.request.HttpRequest;
import com.example.www.http.response.HttpResponse;
import com.example.www.http.response.HttpStringResponse;
import com.example.www.http.client.APICallBack;
import com.example.www.controllers.syncwrapper.APICallBackCatcher;

public class UsersLoginRegistrationController extends BaseController {
    //private static variables for the singleton pattern
    private static final Object syncObject = new Object();
    private static UsersLoginRegistrationController instance = null;

    /**
     * Singleton pattern implementation 
     * @return The singleton instance of the UsersLoginRegistrationController class 
     */
    public static UsersLoginRegistrationController getInstance() {
        if (null == instance) {
            synchronized (syncObject) {
                if (null == instance) {
                    instance = new UsersLoginRegistrationController();
                }
            }
        }
        return instance;
    }

    /**
     * Authenticate to this Bouncer instance.
     * @param    body    Required parameter: Example: 
     * @return    Returns the LoginToBouncerAPIResponse response from the API call 
     */
    public LoginToBouncerAPIResponse loginToBouncerAPI(
                final LoginToBouncerAPIRequest body
    ) throws Throwable {

        HttpRequest _request = _buildLoginToBouncerAPIRequest(body);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleLoginToBouncerAPIResponse(_context);
    }

    /**
     * Authenticate to this Bouncer instance.
     * @param    body    Required parameter: Example: 
     * @return    Returns the void response from the API call 
     */
    public void loginToBouncerAPIAsync(
                final LoginToBouncerAPIRequest body,
                final APICallBack<LoginToBouncerAPIResponse> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildLoginToBouncerAPIRequest(body);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            LoginToBouncerAPIResponse returnValue = _handleLoginToBouncerAPIResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for loginToBouncerAPI
     */
    private HttpRequest _buildLoginToBouncerAPIRequest(
                final LoginToBouncerAPIRequest body) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.getBaseUri();

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/v1.1/login");
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");
        _headers.put("content-type", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().postBody(_queryUrl, _headers, APIHelper.serialize(body));

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        // Custom Authentication to be added for authorization
        CustomAuthUtility.appendCustomAuthParams(_request);

        return _request;
    }

    /**
     * Processes the response for loginToBouncerAPI
     * @return An object of type void
     */
    private LoginToBouncerAPIResponse _handleLoginToBouncerAPIResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 400) {
            throw new ReturnException("Unexpected error in API call. See HTTP response body for details.", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        LoginToBouncerAPIResponse _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<LoginToBouncerAPIResponse>(){});

        return _result;
    }

    /**
     * ONLY AVAILABLE when Bouncer is started with the `--testing` parameter.
     * Register a new user with this instance of Bouncer.
     * @param    body    Required parameter: Example: 
     * @return    Returns the RegisterNewUserResponse response from the API call 
     */
    public RegisterNewUserResponse registerNewUser(
                final RegisterNewUserRequest body
    ) throws Throwable {

        HttpRequest _request = _buildRegisterNewUserRequest(body);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleRegisterNewUserResponse(_context);
    }

    /**
     * ONLY AVAILABLE when Bouncer is started with the `--testing` parameter.
     * Register a new user with this instance of Bouncer.
     * @param    body    Required parameter: Example: 
     * @return    Returns the void response from the API call 
     */
    public void registerNewUserAsync(
                final RegisterNewUserRequest body,
                final APICallBack<RegisterNewUserResponse> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildRegisterNewUserRequest(body);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            RegisterNewUserResponse returnValue = _handleRegisterNewUserResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for registerNewUser
     */
    private HttpRequest _buildRegisterNewUserRequest(
                final RegisterNewUserRequest body) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.getBaseUri();

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/v1.1/register");
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");
        _headers.put("content-type", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().postBody(_queryUrl, _headers, APIHelper.serialize(body));

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        // Custom Authentication to be added for authorization
        CustomAuthUtility.appendCustomAuthParams(_request);

        return _request;
    }

    /**
     * Processes the response for registerNewUser
     * @return An object of type void
     */
    private RegisterNewUserResponse _handleRegisterNewUserResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 400) {
            throw new ReturnException("Unexpected error in API call. See HTTP response body for details.", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        RegisterNewUserResponse _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<RegisterNewUserResponse>(){});

        return _result;
    }

}
