# -*- coding: utf-8 -*-

"""
    bouncerapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import bouncerapi.models.result
import bouncerapi.models.ip_address

class GetDetailsResponse(object):

    """Implementation of the 'Get Details response' model.

    TODO: type model description here.

    Attributes:
        result (Result): TODO: type description here.
        entry (IPAddress): The IP address information referenced by Bouncer
            when building `ufw` rules

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "result":'Result',
        "entry":'Entry'
    }

    def __init__(self,
                 result=None,
                 entry=None):
        """Constructor for the GetDetailsResponse class"""

        # Initialize members of the class
        self.result = result
        self.entry = entry


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        result = bouncerapi.models.result.Result.from_dictionary(dictionary.get('Result')) if dictionary.get('Result') else None
        entry = bouncerapi.models.ip_address.IPAddress.from_dictionary(dictionary.get('Entry')) if dictionary.get('Entry') else None

        # Return an object of this model
        return cls(result,
                   entry)


