# -*- coding: utf-8 -*-

"""
    bouncerapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import bouncerapi.models.result

class ListResponse1(object):

    """Implementation of the 'List response1' model.

    TODO: type model description here.

    Attributes:
        result (Result): TODO: type description here.
        geo_locations (list of string): matching Geo Location Objects (in
            short string form `{id}#{cc}`) found

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "result":'Result',
        "geo_locations":'GeoLocations'
    }

    def __init__(self,
                 result=None,
                 geo_locations=None):
        """Constructor for the ListResponse1 class"""

        # Initialize members of the class
        self.result = result
        self.geo_locations = geo_locations


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        result = bouncerapi.models.result.Result.from_dictionary(dictionary.get('Result')) if dictionary.get('Result') else None
        geo_locations = dictionary.get('GeoLocations')

        # Return an object of this model
        return cls(result,
                   geo_locations)


