# -*- coding: utf-8 -*-

"""
    bouncerapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class ListEnum(object):

    """Implementation of the 'List' enum.

    TODO: type enum description here.

    Attributes:
        WHITELIST: TODO: type description here.
        BLACKLIST: TODO: type description here.

    """

    WHITELIST = 'Whitelist'

    BLACKLIST = 'Blacklist'

