# -*- coding: utf-8 -*-

"""
    bouncerapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class LoginToBouncerAPIResponse(object):

    """Implementation of the 'Login to Bouncer API response' model.

    TODO: type model description here.

    Attributes:
        access_token (string): the access token to use in all future requests
        token_type (string): always `bearer`
        expires_in (string): the expiry of this bearer token in seconds
        claim_level (string): always `complete`

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "access_token":'access_token',
        "token_type":'token_type',
        "expires_in":'expires_in',
        "claim_level":'claim_level'
    }

    def __init__(self,
                 access_token=None,
                 token_type=None,
                 expires_in=None,
                 claim_level=None):
        """Constructor for the LoginToBouncerAPIResponse class"""

        # Initialize members of the class
        self.access_token = access_token
        self.token_type = token_type
        self.expires_in = expires_in
        self.claim_level = claim_level


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        access_token = dictionary.get('access_token')
        token_type = dictionary.get('token_type')
        expires_in = dictionary.get('expires_in')
        claim_level = dictionary.get('claim_level')

        # Return an object of this model
        return cls(access_token,
                   token_type,
                   expires_in,
                   claim_level)


