# -*- coding: utf-8 -*-

"""
    bouncerapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import bouncerapi.models.result
import bouncerapi.models.search_result

class SearchResponse(object):

    """Implementation of the 'Search response' model.

    TODO: type model description here.

    Attributes:
        result (Result): TODO: type description here.
        search_result (SearchResult): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "result":'Result',
        "search_result":'SearchResult'
    }

    def __init__(self,
                 result=None,
                 search_result=None):
        """Constructor for the SearchResponse class"""

        # Initialize members of the class
        self.result = result
        self.search_result = search_result


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        result = bouncerapi.models.result.Result.from_dictionary(dictionary.get('Result')) if dictionary.get('Result') else None
        search_result = bouncerapi.models.search_result.SearchResult.from_dictionary(dictionary.get('SearchResult')) if dictionary.get('SearchResult') else None

        # Return an object of this model
        return cls(result,
                   search_result)


