/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www;

import java.util.HashMap;
import java.util.Map;

import com.example.www.models.*;

public class Configuration {
    /**
     * Current API environment
     */
    public static Environments environment = Environments.PRODUCTION;

    /**
     *  defaultHost value
     */
    public static String defaultHost = "www.example.com";

    /**
     * Get base URI by current environment
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public static String getBaseUri(Servers server) {
        StringBuilder baseUrl = new StringBuilder(environmentMapper(Configuration.environment, server));
        Map<String, Object> parameters = new HashMap<String, Object>();
		parameters.put("defaultHost", Configuration.defaultHost);
        APIHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }
    
    /**
     * Get base URI by current environment
     * @return Processed base URI
     */
    public static String getBaseUri() {
        return Configuration.getBaseUri(Servers.ENUM_DEFAULT);
    }
    
    /**
     * Base URLs by environments and server aliases 
     */

    private static String environmentMapper(Environments environments, Servers servers) {
		String url = "";
		if(environments.equals(Environments.PRODUCTION)) {
			if(servers.equals(Servers.ENUM_DEFAULT))
				url = "http://{defaultHost}";
		}
		return url;
	}
}
