/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.exceptions;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.example.www.http.client.HttpContext;

public class ReturnException 
        extends APIException
        implements java.io.Serializable {
    private static final long serialVersionUID = 3365776788105673388L;
    private String status;
    private String error;
    /** GETTER
     * The status of the return
     */
    @JsonGetter("Status")
    public String getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * The status of the return
     */
    @JsonSetter("Status")
    private void setStatus (String value) { 
        this.status = value;
    }
 
    /** GETTER
     * the error value
     */
    @JsonGetter("Error")
    public String getError ( ) { 
        return this.error;
    }
    
    /** SETTER
     * the error value
     */
    @JsonSetter("Error")
    private void setError (String value) { 
        this.error = value;
    }
 
    /**
     * Initialization constructor
     * @param   reason  The reason for throwing exception
     * @param   context The http context of the API exception
     */
    public ReturnException(String reason, HttpContext context) {
        super(reason, context);
    }
}
