# -*- coding: utf-8 -*-

"""
    bouncerapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from bouncerapi.decorators import lazy_property
from bouncerapi.configuration import Configuration
from bouncerapi.controllers.blacklist_controller import BlacklistController
from bouncerapi.controllers.users_login_registration_controller import UsersLoginRegistrationController
from bouncerapi.controllers.whitelist_geo_locations_controller import WhitelistGeoLocationsController
from bouncerapi.controllers.blacklist_geo_locations_controller import BlacklistGeoLocationsController
from bouncerapi.controllers.check_ip_addresses_controller import CheckIPAddressesController
from bouncerapi.controllers.blacklist_ip_addresses_controller import BlacklistIPAddressesController
from bouncerapi.controllers.whitelist_ip_addresses_controller import WhitelistIPAddressesController
from bouncerapi.controllers.whitelist_controller import WhitelistController


class BouncerapiClient(object):

    config = Configuration

    @lazy_property
    def blacklist(self):
        return BlacklistController()

    @lazy_property
    def users_login_registration(self):
        return UsersLoginRegistrationController()

    @lazy_property
    def whitelist_geo_locations(self):
        return WhitelistGeoLocationsController()

    @lazy_property
    def blacklist_geo_locations(self):
        return BlacklistGeoLocationsController()

    @lazy_property
    def check_ip_addresses(self):
        return CheckIPAddressesController()

    @lazy_property
    def blacklist_ip_addresses(self):
        return BlacklistIPAddressesController()

    @lazy_property
    def whitelist_ip_addresses(self):
        return WhitelistIPAddressesController()

    @lazy_property
    def whitelist(self):
        return WhitelistController()


