/*
 * BouncerAPI.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using BouncerAPI.Standard;
using BouncerAPI.Standard.Utilities; 
using BouncerAPI.Standard.Http.Client;
using BouncerAPI.Standard.Http.Response;
using BouncerAPI.Tests.Helpers;
using NUnit.Framework;
using BouncerAPI.Standard;
using BouncerAPI.Standard.Controllers;
using BouncerAPI.Standard.Exceptions;

namespace BouncerAPI.Tests
{
    [TestFixture]
    public class BlacklistIPAddressesControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static BlacklistIPAddressesController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [SetUp]
        public static void SetUpClass()
        {
            controller = GetClient().BlacklistIPAddresses;
        }

        /// <summary>
        /// Get Details of an IP Address Entry in the Blacklist 
        /// </summary>
        [Test]
        public async Task TestGetDetails1() 
        {
            // Parameters for the API call
            string entryId = "884d9804999fc47a3c2694e49ad2536a";

            // Perform API call
            Standard.Models.GetDetailsResponse result = null;

            try
            {
                result = await controller.GetDetailsAsync(entryId);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", null);

            Assert.IsTrue(TestHelper.AreHeadersProperSubsetOf (
                    headers, httpCallBackHandler.Response.Headers),
                    "Headers should match");

            // Test whether the captured response is as we expected
            Assert.IsNotNull(result, "Result should exist");

            Assert.AreEqual("{  \"Result\": {    \"Status\": \"Success\",    \"Message\": \"\"  },  \"Entry\": {    \"IPv4\": \"192.168.100.14/24\",    \"IPv6\": \"2001:db8::/64\",    \"Start_Date\": \"2019-04-05T02:04:16Z\",    \"End_Date\": \"2019-04-05T02:04:16Z\",    \"Comments\": \"noteworthy note\",    \"Active\": true  }}", 
                    TestHelper.ConvertStreamToString(httpCallBackHandler.Response.RawBody),
                    "Response body should match exactly (string literal match)");
        }

        /// <summary>
        /// Search for IP Addresses in the Blacklist 
        /// </summary>
        [Test]
        public async Task TestSearch1() 
        {
            // Parameters for the API call
            string searchFilter = "192.168.100.0+24,192.168.101.0+24";

            // Perform API call
            Standard.Models.SearchResponse result = null;

            try
            {
                result = await controller.SearchAsync(searchFilter);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", null);

            Assert.IsTrue(TestHelper.AreHeadersProperSubsetOf (
                    headers, httpCallBackHandler.Response.Headers),
                    "Headers should match");

            // Test whether the captured response is as we expected
            Assert.IsNotNull(result, "Result should exist");

            Assert.AreEqual("{  \"Result\": {    \"Status\": \"Success\",    \"Message\": \"\"  },  \"SearchResult\": {    \"Input_IP\": \"192.168.100.0/24,192.168.101.0/24\",    \"Entries\": [      {        \"EntryID\": \"884d9804999fc47a3c2694e49ad2536a\",        \"IPv4\": \"192.168.100.14/24\"      }    ]  }}", 
                    TestHelper.ConvertStreamToString(httpCallBackHandler.Response.RawBody),
                    "Response body should match exactly (string literal match)");
        }

        /// <summary>
        /// List all IP Addresses in the Blacklist 
        /// </summary>
        [Test]
        public async Task TestList1() 
        {

            // Perform API call
            Standard.Models.ListResponse result = null;

            try
            {
                result = await controller.ListAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", null);

            Assert.IsTrue(TestHelper.AreHeadersProperSubsetOf (
                    headers, httpCallBackHandler.Response.Headers),
                    "Headers should match");

            // Test whether the captured response is as we expected
            Assert.IsNotNull(result, "Result should exist");

            Assert.AreEqual("{  \"Result\": {    \"Status\": \"Success\",    \"Message\": \"\"  },  \"IPAddresses\": [    [      \"884d9804999fc47a3c2694e49ad2536a\",      \"192.168.100.14/24\"    ]  ]}", 
                    TestHelper.ConvertStreamToString(httpCallBackHandler.Response.RawBody),
                    "Response body should match exactly (string literal match)");
        }

    }
}