/*
 * BouncerAPI.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using BouncerAPI.Standard;
using BouncerAPI.Standard.Utilities; 
using BouncerAPI.Standard.Http.Client;
using BouncerAPI.Standard.Http.Response;
using BouncerAPI.Tests.Helpers;
using NUnit.Framework;
using BouncerAPI.Standard;
using BouncerAPI.Standard.Controllers;
using BouncerAPI.Standard.Exceptions;

namespace BouncerAPI.Tests
{
    [TestFixture]
    public class WhitelistGeoLocationsControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static WhitelistGeoLocationsController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [SetUp]
        public static void SetUpClass()
        {
            controller = GetClient().WhitelistGeoLocations;
        }

        /// <summary>
        /// Get Details of a Geo Location Entry in the Whitelist 
        /// </summary>
        [Test]
        public async Task TestGetDetails1() 
        {
            // Parameters for the API call
            string entryId = "884d9804999fc47a3c2694e49ad2536a";

            // Perform API call
            Standard.Models.GetDetailsResponse1 result = null;

            try
            {
                result = await controller.GetDetailsAsync(entryId);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", null);

            Assert.IsTrue(TestHelper.AreHeadersProperSubsetOf (
                    headers, httpCallBackHandler.Response.Headers),
                    "Headers should match");

            // Test whether the captured response is as we expected
            Assert.IsNotNull(result, "Result should exist");

            Assert.AreEqual("{  \"Result\": {    \"Status\": \"Success\",    \"Message\": \"\"  },  \"Entry\": {    \"Country Code\": \"CA\",    \"Start_Date\": \"2019-04-05T02:04:16Z\",    \"End_Date\": \"2019-04-05T02:04:16Z\",    \"Comments\": \"noteworthy note\",    \"Active\": true  }}", 
                    TestHelper.ConvertStreamToString(httpCallBackHandler.Response.RawBody),
                    "Response body should match exactly (string literal match)");
        }

        /// <summary>
        /// List all Geo Locations in the Whitelist 
        /// </summary>
        [Test]
        public async Task TestList1() 
        {

            // Perform API call
            Standard.Models.ListResponse1 result = null;

            try
            {
                result = await controller.ListAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", null);

            Assert.IsTrue(TestHelper.AreHeadersProperSubsetOf (
                    headers, httpCallBackHandler.Response.Headers),
                    "Headers should match");

            // Test whether the captured response is as we expected
            Assert.IsNotNull(result, "Result should exist");

            Assert.AreEqual("{  \"Result\": {    \"Status\": \"Success\",    \"Message\": \"\"  },  \"GeoLocations\": [    \"884d9804999fc47a3c2694e49ad2536a#CA\"  ]}", 
                    TestHelper.ConvertStreamToString(httpCallBackHandler.Response.RawBody),
                    "Response body should match exactly (string literal match)");
        }

    }
}