/*
 * BouncerAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using BouncerAPI.Standard.Controllers;
using BouncerAPI.Standard.Http.Client;
using BouncerAPI.Standard.Utilities;

namespace BouncerAPI.Standard
{
    public partial class BouncerAPIClient
    {

        /// <summary>
        /// Singleton access to Blacklist controller
        /// </summary>
        public BlacklistController Blacklist
        {
            get
            {
                return BlacklistController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to UsersLoginRegistration controller
        /// </summary>
        public UsersLoginRegistrationController UsersLoginRegistration
        {
            get
            {
                return UsersLoginRegistrationController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to WhitelistGeoLocations controller
        /// </summary>
        public WhitelistGeoLocationsController WhitelistGeoLocations
        {
            get
            {
                return WhitelistGeoLocationsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to BlacklistGeoLocations controller
        /// </summary>
        public BlacklistGeoLocationsController BlacklistGeoLocations
        {
            get
            {
                return BlacklistGeoLocationsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to CheckIPAddresses controller
        /// </summary>
        public CheckIPAddressesController CheckIPAddresses
        {
            get
            {
                return CheckIPAddressesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to BlacklistIPAddresses controller
        /// </summary>
        public BlacklistIPAddressesController BlacklistIPAddresses
        {
            get
            {
                return BlacklistIPAddressesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to WhitelistIPAddresses controller
        /// </summary>
        public WhitelistIPAddressesController WhitelistIPAddresses
        {
            get
            {
                return WhitelistIPAddressesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Whitelist controller
        /// </summary>
        public WhitelistController Whitelist
        {
            get
            {
                return WhitelistController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public BouncerAPIClient() { }
        #endregion
    }
}