/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class AllContentsResponseBuilder {
    //the instance to build
    private AllContentsResponse allContentsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public AllContentsResponseBuilder() {
        allContentsResponse = new AllContentsResponse();
    }

    public AllContentsResponseBuilder result(Result result) {
        allContentsResponse.setResult(result);
        return this;
    }

    /**
     * matching IP Address Objects found
     */
    public AllContentsResponseBuilder iPAddresses(List<String> iPAddresses) {
        allContentsResponse.setIPAddresses(iPAddresses);
        return this;
    }

    /**
     * matching Geo Location Objects (in short string form `{id}#{cc}`) found
     */
    public AllContentsResponseBuilder geoLocations(List<String> geoLocations) {
        allContentsResponse.setGeoLocations(geoLocations);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AllContentsResponse build() {
        return allContentsResponse;
    }
}