/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class CreateResponse1Builder {
    //the instance to build
    private CreateResponse1 createResponse1;

    /**
     * Default constructor to initialize the instance
     */
    public CreateResponse1Builder() {
        createResponse1 = new CreateResponse1();
    }

    public CreateResponse1Builder result(Result9 result) {
        createResponse1.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateResponse1 build() {
        return createResponse1;
    }
}