/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class CreateResponseBuilder {
    //the instance to build
    private CreateResponse createResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CreateResponseBuilder() {
        createResponse = new CreateResponse();
    }

    public CreateResponseBuilder result(Result4 result) {
        createResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateResponse build() {
        return createResponse;
    }
}