/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class GeoLocationBuilder {
    //the instance to build
    private GeoLocation geoLocation;

    /**
     * Default constructor to initialize the instance
     */
    public GeoLocationBuilder() {
        geoLocation = new GeoLocation();
    }

    /**
     * ISO Country Code
     */
    public GeoLocationBuilder countryCode(String countryCode) {
        geoLocation.setCountryCode(countryCode);
        return this;
    }

    /**
     * Starting UTC Date and time for entry
     */
    public GeoLocationBuilder startDate(String startDate) {
        geoLocation.setStartDate(startDate);
        return this;
    }

    /**
     * Ending UTC Date and time for entry
     */
    public GeoLocationBuilder endDate(String endDate) {
        geoLocation.setEndDate(endDate);
        return this;
    }

    /**
     * Any notes or description for the entry, maximum length of 3000 characters
     */
    public GeoLocationBuilder comments(String comments) {
        geoLocation.setComments(comments);
        return this;
    }

    /**
     * Identifies if the entry is active
     */
    public GeoLocationBuilder active(boolean active) {
        geoLocation.setActive(active);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GeoLocation build() {
        return geoLocation;
    }
}