/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class GeoLocation 
        implements java.io.Serializable {
    private static final long serialVersionUID = 2751050166399476338L;
    private String countryCode;
    private String startDate;
    private String endDate;
    private String comments;
    private boolean active;
    /** GETTER
     * ISO Country Code
     */
    @JsonGetter("Country Code")
    public String getCountryCode ( ) { 
        return this.countryCode;
    }
    
    /** SETTER
     * ISO Country Code
     */
    @JsonSetter("Country Code")
    public void setCountryCode (String value) { 
        this.countryCode = value;
    }
 
    /** GETTER
     * Starting UTC Date and time for entry
     */
    @JsonGetter("Start_Date")
    public String getStartDate ( ) { 
        return this.startDate;
    }
    
    /** SETTER
     * Starting UTC Date and time for entry
     */
    @JsonSetter("Start_Date")
    public void setStartDate (String value) { 
        this.startDate = value;
    }
 
    /** GETTER
     * Ending UTC Date and time for entry
     */
    @JsonGetter("End_Date")
    public String getEndDate ( ) { 
        return this.endDate;
    }
    
    /** SETTER
     * Ending UTC Date and time for entry
     */
    @JsonSetter("End_Date")
    public void setEndDate (String value) { 
        this.endDate = value;
    }
 
    /** GETTER
     * Any notes or description for the entry, maximum length of 3000 characters
     */
    @JsonGetter("Comments")
    public String getComments ( ) { 
        return this.comments;
    }
    
    /** SETTER
     * Any notes or description for the entry, maximum length of 3000 characters
     */
    @JsonSetter("Comments")
    public void setComments (String value) { 
        this.comments = value;
    }
 
    /** GETTER
     * Identifies if the entry is active
     */
    @JsonGetter("Active")
    public boolean getActive ( ) { 
        return this.active;
    }
    
    /** SETTER
     * Identifies if the entry is active
     */
    @JsonSetter("Active")
    public void setActive (boolean value) { 
        this.active = value;
    }
 
}
