/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class GetDetailsResponse1Builder {
    //the instance to build
    private GetDetailsResponse1 getDetailsResponse1;

    /**
     * Default constructor to initialize the instance
     */
    public GetDetailsResponse1Builder() {
        getDetailsResponse1 = new GetDetailsResponse1();
    }

    public GetDetailsResponse1Builder result(Result result) {
        getDetailsResponse1.setResult(result);
        return this;
    }

    /**
     * The geolocation information referenced by Bouncer when building `ufw` rules
     */
    public GetDetailsResponse1Builder entry(GeoLocation entry) {
        getDetailsResponse1.setEntry(entry);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetDetailsResponse1 build() {
        return getDetailsResponse1;
    }
}