/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class GetDetailsResponseBuilder {
    //the instance to build
    private GetDetailsResponse getDetailsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetDetailsResponseBuilder() {
        getDetailsResponse = new GetDetailsResponse();
    }

    public GetDetailsResponseBuilder result(Result result) {
        getDetailsResponse.setResult(result);
        return this;
    }

    /**
     * The IP address information referenced by Bouncer when building `ufw` rules
     */
    public GetDetailsResponseBuilder entry(IPAddress entry) {
        getDetailsResponse.setEntry(entry);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetDetailsResponse build() {
        return getDetailsResponse;
    }
}