/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class IPAddressEntryPairBuilder {
    //the instance to build
    private IPAddressEntryPair iPAddressEntryPair;

    /**
     * Default constructor to initialize the instance
     */
    public IPAddressEntryPairBuilder() {
        iPAddressEntryPair = new IPAddressEntryPair();
    }

    /**
     * a unique identifier for the newly created Geo Location; opaque but likely a GUID
     */
    public IPAddressEntryPairBuilder entryID(String entryID) {
        iPAddressEntryPair.setEntryID(entryID);
        return this;
    }

    /**
     * IP Address v4 in CIDR Format. Either IPv4 or IPv6 MUST be present.
     */
    public IPAddressEntryPairBuilder iPv4(String iPv4) {
        iPAddressEntryPair.setIPv4(iPv4);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public IPAddressEntryPair build() {
        return iPAddressEntryPair;
    }
}