/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class IPAddressBuilder {
    //the instance to build
    private IPAddress iPAddress;

    /**
     * Default constructor to initialize the instance
     */
    public IPAddressBuilder() {
        iPAddress = new IPAddress();
    }

    /**
     * IP Address v4 in CIDR Format. Either IPv4 or IPv6 MUST be present.
     */
    public IPAddressBuilder iPv4(String iPv4) {
        iPAddress.setIPv4(iPv4);
        return this;
    }

    /**
     * IP Address v6 in CIDR Format. Either IPv4 or IPv6 MUST be present.
     */
    public IPAddressBuilder iPv6(String iPv6) {
        iPAddress.setIPv6(iPv6);
        return this;
    }

    /**
     * Starting UTC Date and time for entry
     */
    public IPAddressBuilder startDate(String startDate) {
        iPAddress.setStartDate(startDate);
        return this;
    }

    /**
     * Ending UTC Date and time for entry
     */
    public IPAddressBuilder endDate(String endDate) {
        iPAddress.setEndDate(endDate);
        return this;
    }

    /**
     * Any notes or description for the entry, maximum length of 3000 characters
     */
    public IPAddressBuilder comments(String comments) {
        iPAddress.setComments(comments);
        return this;
    }

    /**
     * Identifies if the entry is active
     */
    public IPAddressBuilder active(boolean active) {
        iPAddress.setActive(active);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public IPAddress build() {
        return iPAddress;
    }
}