/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class IPAddress 
        implements java.io.Serializable {
    private static final long serialVersionUID = -8524568962675029120L;
    private String iPv4;
    private String iPv6;
    private String startDate;
    private String endDate;
    private String comments;
    private boolean active;
    /** GETTER
     * IP Address v4 in CIDR Format. Either IPv4 or IPv6 MUST be present.
     */
    @JsonGetter("IPv4")
    public String getIPv4 ( ) { 
        return this.iPv4;
    }
    
    /** SETTER
     * IP Address v4 in CIDR Format. Either IPv4 or IPv6 MUST be present.
     */
    @JsonSetter("IPv4")
    public void setIPv4 (String value) { 
        this.iPv4 = value;
    }
 
    /** GETTER
     * IP Address v6 in CIDR Format. Either IPv4 or IPv6 MUST be present.
     */
    @JsonGetter("IPv6")
    public String getIPv6 ( ) { 
        return this.iPv6;
    }
    
    /** SETTER
     * IP Address v6 in CIDR Format. Either IPv4 or IPv6 MUST be present.
     */
    @JsonSetter("IPv6")
    public void setIPv6 (String value) { 
        this.iPv6 = value;
    }
 
    /** GETTER
     * Starting UTC Date and time for entry
     */
    @JsonGetter("Start_Date")
    public String getStartDate ( ) { 
        return this.startDate;
    }
    
    /** SETTER
     * Starting UTC Date and time for entry
     */
    @JsonSetter("Start_Date")
    public void setStartDate (String value) { 
        this.startDate = value;
    }
 
    /** GETTER
     * Ending UTC Date and time for entry
     */
    @JsonGetter("End_Date")
    public String getEndDate ( ) { 
        return this.endDate;
    }
    
    /** SETTER
     * Ending UTC Date and time for entry
     */
    @JsonSetter("End_Date")
    public void setEndDate (String value) { 
        this.endDate = value;
    }
 
    /** GETTER
     * Any notes or description for the entry, maximum length of 3000 characters
     */
    @JsonGetter("Comments")
    public String getComments ( ) { 
        return this.comments;
    }
    
    /** SETTER
     * Any notes or description for the entry, maximum length of 3000 characters
     */
    @JsonSetter("Comments")
    public void setComments (String value) { 
        this.comments = value;
    }
 
    /** GETTER
     * Identifies if the entry is active
     */
    @JsonGetter("Active")
    public boolean getActive ( ) { 
        return this.active;
    }
    
    /** SETTER
     * Identifies if the entry is active
     */
    @JsonSetter("Active")
    public void setActive (boolean value) { 
        this.active = value;
    }
 
}
