/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class ListResponse1Builder {
    //the instance to build
    private ListResponse1 listResponse1;

    /**
     * Default constructor to initialize the instance
     */
    public ListResponse1Builder() {
        listResponse1 = new ListResponse1();
    }

    public ListResponse1Builder result(Result result) {
        listResponse1.setResult(result);
        return this;
    }

    /**
     * matching Geo Location Objects (in short string form `{id}#{cc}`) found
     */
    public ListResponse1Builder geoLocations(List<String> geoLocations) {
        listResponse1.setGeoLocations(geoLocations);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ListResponse1 build() {
        return listResponse1;
    }
}