/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class ListResponseBuilder {
    //the instance to build
    private ListResponse listResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ListResponseBuilder() {
        listResponse = new ListResponse();
    }

    public ListResponseBuilder result(Result result) {
        listResponse.setResult(result);
        return this;
    }

    /**
     * matching IP Address Objects found
     */
    public ListResponseBuilder iPAddresses(List<String> iPAddresses) {
        listResponse.setIPAddresses(iPAddresses);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ListResponse build() {
        return listResponse;
    }
}