/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum ListEnum {
    WHITELIST, //TODO: Write general description for this element
    BLACKLIST; //TODO: Write general description for this element

    private static TreeMap<String, ListEnum> valueMap = new TreeMap<String, ListEnum>();
    private String value;

    static {
        WHITELIST.value = "Whitelist";
        BLACKLIST.value = "Blacklist";

        valueMap.put("Whitelist", WHITELIST);
        valueMap.put("Blacklist", BLACKLIST);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static ListEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ListEnum values to list of string values
     * @param toConvert The list of ListEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<ListEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (ListEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 