/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class LoginToBouncerAPIResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 7127463714392008937L;
    private String accessToken;
    private String tokenType;
    private String expiresIn;
    private String claimLevel;
    /** GETTER
     * the access token to use in all future requests
     */
    @JsonGetter("access_token")
    public String getAccessToken ( ) { 
        return this.accessToken;
    }
    
    /** SETTER
     * the access token to use in all future requests
     */
    @JsonSetter("access_token")
    public void setAccessToken (String value) { 
        this.accessToken = value;
    }
 
    /** GETTER
     * always `bearer`
     */
    @JsonGetter("token_type")
    public String getTokenType ( ) { 
        return this.tokenType;
    }
    
    /** SETTER
     * always `bearer`
     */
    @JsonSetter("token_type")
    public void setTokenType (String value) { 
        this.tokenType = value;
    }
 
    /** GETTER
     * the expiry of this bearer token in seconds
     */
    @JsonGetter("expires_in")
    public String getExpiresIn ( ) { 
        return this.expiresIn;
    }
    
    /** SETTER
     * the expiry of this bearer token in seconds
     */
    @JsonSetter("expires_in")
    public void setExpiresIn (String value) { 
        this.expiresIn = value;
    }
 
    /** GETTER
     * always `complete`
     */
    @JsonGetter("claim_level")
    public String getClaimLevel ( ) { 
        return this.claimLevel;
    }
    
    /** SETTER
     * always `complete`
     */
    @JsonSetter("claim_level")
    public void setClaimLevel (String value) { 
        this.claimLevel = value;
    }
 
}
