/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class LoginToBouncerAPIResponseBuilder {
    //the instance to build
    private LoginToBouncerAPIResponse loginToBouncerAPIResponse;

    /**
     * Default constructor to initialize the instance
     */
    public LoginToBouncerAPIResponseBuilder() {
        loginToBouncerAPIResponse = new LoginToBouncerAPIResponse();
    }

    /**
     * the access token to use in all future requests
     */
    public LoginToBouncerAPIResponseBuilder accessToken(String accessToken) {
        loginToBouncerAPIResponse.setAccessToken(accessToken);
        return this;
    }

    /**
     * always `bearer`
     */
    public LoginToBouncerAPIResponseBuilder tokenType(String tokenType) {
        loginToBouncerAPIResponse.setTokenType(tokenType);
        return this;
    }

    /**
     * the expiry of this bearer token in seconds
     */
    public LoginToBouncerAPIResponseBuilder expiresIn(String expiresIn) {
        loginToBouncerAPIResponse.setExpiresIn(expiresIn);
        return this;
    }

    /**
     * always `complete`
     */
    public LoginToBouncerAPIResponseBuilder claimLevel(String claimLevel) {
        loginToBouncerAPIResponse.setClaimLevel(claimLevel);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LoginToBouncerAPIResponse build() {
        return loginToBouncerAPIResponse;
    }
}