/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class LoginToBouncerAPIRequestBuilder {
    //the instance to build
    private LoginToBouncerAPIRequest loginToBouncerAPIRequest;

    /**
     * Default constructor to initialize the instance
     */
    public LoginToBouncerAPIRequestBuilder() {
        loginToBouncerAPIRequest = new LoginToBouncerAPIRequest();
    }

    public LoginToBouncerAPIRequestBuilder username(String username) {
        loginToBouncerAPIRequest.setUsername(username);
        return this;
    }

    public LoginToBouncerAPIRequestBuilder password(String password) {
        loginToBouncerAPIRequest.setPassword(password);
        return this;
    }

    /**
     * must be `password`
     */
    public LoginToBouncerAPIRequestBuilder grantType(String grantType) {
        loginToBouncerAPIRequest.setGrantType(grantType);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LoginToBouncerAPIRequest build() {
        return loginToBouncerAPIRequest;
    }
}