/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class RegisterNewUserResponseBuilder {
    //the instance to build
    private RegisterNewUserResponse registerNewUserResponse;

    /**
     * Default constructor to initialize the instance
     */
    public RegisterNewUserResponseBuilder() {
        registerNewUserResponse = new RegisterNewUserResponse();
    }

    public RegisterNewUserResponseBuilder message(String message) {
        registerNewUserResponse.setMessage(message);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RegisterNewUserResponse build() {
        return registerNewUserResponse;
    }
}