/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class RegisterNewUserRequestBuilder {
    //the instance to build
    private RegisterNewUserRequest registerNewUserRequest;

    /**
     * Default constructor to initialize the instance
     */
    public RegisterNewUserRequestBuilder() {
        registerNewUserRequest = new RegisterNewUserRequest();
    }

    /**
     * new username
     */
    public RegisterNewUserRequestBuilder username(String username) {
        registerNewUserRequest.setUsername(username);
        return this;
    }

    /**
     * new user's password
     */
    public RegisterNewUserRequestBuilder password(String password) {
        registerNewUserRequest.setPassword(password);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RegisterNewUserRequest build() {
        return registerNewUserRequest;
    }
}