/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class RemoveResponse1Builder {
    //the instance to build
    private RemoveResponse1 removeResponse1;

    /**
     * Default constructor to initialize the instance
     */
    public RemoveResponse1Builder() {
        removeResponse1 = new RemoveResponse1();
    }

    public RemoveResponse1Builder result(Result11 result) {
        removeResponse1.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RemoveResponse1 build() {
        return removeResponse1;
    }
}