/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class RemoveResponseBuilder {
    //the instance to build
    private RemoveResponse removeResponse;

    /**
     * Default constructor to initialize the instance
     */
    public RemoveResponseBuilder() {
        removeResponse = new RemoveResponse();
    }

    public RemoveResponseBuilder result(Result6 result) {
        removeResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RemoveResponse build() {
        return removeResponse;
    }
}