/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class Result4Builder {
    //the instance to build
    private Result4 result4;

    /**
     * Default constructor to initialize the instance
     */
    public Result4Builder() {
        result4 = new Result4();
    }

    public Result4Builder status(String status) {
        result4.setStatus(status);
        return this;
    }

    /**
     * an optional message
     */
    public Result4Builder message(String message) {
        result4.setMessage(message);
        return this;
    }

    /**
     * a unique identifier for the newly created IP Address; opaque but likely a GUID
     */
    public Result4Builder entryID(String entryID) {
        result4.setEntryID(entryID);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Result4 build() {
        return result4;
    }
}