/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class ResultBuilder {
    //the instance to build
    private Result result;

    /**
     * Default constructor to initialize the instance
     */
    public ResultBuilder() {
        result = new Result();
    }

    public ResultBuilder status(String status) {
        result.setStatus(status);
        return this;
    }

    /**
     * an optional message
     */
    public ResultBuilder message(String message) {
        result.setMessage(message);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Result build() {
        return result;
    }
}