/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Result24 
        implements java.io.Serializable {
    private static final long serialVersionUID = -6277568749899215198L;
    private ListEnum list;
    private String status;
    private String message;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("List")
    public ListEnum getList ( ) { 
        return this.list;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("List")
    public void setList (ListEnum value) { 
        this.list = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Status")
    public String getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Status")
    public void setStatus (String value) { 
        this.status = value;
    }
 
    /** GETTER
     * an optional message
     */
    @JsonGetter("Message")
    public String getMessage ( ) { 
        return this.message;
    }
    
    /** SETTER
     * an optional message
     */
    @JsonSetter("Message")
    public void setMessage (String value) { 
        this.message = value;
    }
 
}
