/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Result6 
        implements java.io.Serializable {
    private static final long serialVersionUID = 1834128003015287845L;
    private String status;
    private String message;
    private String entryID;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Status")
    public String getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Status")
    public void setStatus (String value) { 
        this.status = value;
    }
 
    /** GETTER
     * an optional message
     */
    @JsonGetter("Message")
    public String getMessage ( ) { 
        return this.message;
    }
    
    /** SETTER
     * an optional message
     */
    @JsonSetter("Message")
    public void setMessage (String value) { 
        this.message = value;
    }
 
    /** GETTER
     * a unique identifier for the deleted IP Address ; opaque but likely a GUID
     */
    @JsonGetter("EntryID")
    public String getEntryID ( ) { 
        return this.entryID;
    }
    
    /** SETTER
     * a unique identifier for the deleted IP Address ; opaque but likely a GUID
     */
    @JsonSetter("EntryID")
    public void setEntryID (String value) { 
        this.entryID = value;
    }
 
}
