/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class Result24Builder {
    //the instance to build
    private Result24 result24;

    /**
     * Default constructor to initialize the instance
     */
    public Result24Builder() {
        result24 = new Result24();
    }

    public Result24Builder list(ListEnum list) {
        result24.setList(list);
        return this;
    }

    public Result24Builder status(String status) {
        result24.setStatus(status);
        return this;
    }

    /**
     * an optional message
     */
    public Result24Builder message(String message) {
        result24.setMessage(message);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Result24 build() {
        return result24;
    }
}