/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class Result9Builder {
    //the instance to build
    private Result9 result9;

    /**
     * Default constructor to initialize the instance
     */
    public Result9Builder() {
        result9 = new Result9();
    }

    public Result9Builder status(String status) {
        result9.setStatus(status);
        return this;
    }

    /**
     * an optional message
     */
    public Result9Builder message(String message) {
        result9.setMessage(message);
        return this;
    }

    /**
     * a unique identifier for the newly created Geo Location; opaque but likely a GUID
     */
    public Result9Builder entryID(String entryID) {
        result9.setEntryID(entryID);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Result9 build() {
        return result9;
    }
}