/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class Result10Builder {
    //the instance to build
    private Result10 result10;

    /**
     * Default constructor to initialize the instance
     */
    public Result10Builder() {
        result10 = new Result10();
    }

    public Result10Builder status(String status) {
        result10.setStatus(status);
        return this;
    }

    /**
     * an optional message
     */
    public Result10Builder message(String message) {
        result10.setMessage(message);
        return this;
    }

    /**
     * a unique identifier for the newly updated Geo Location; opaque but likely a GUID
     */
    public Result10Builder entryID(String entryID) {
        result10.setEntryID(entryID);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Result10 build() {
        return result10;
    }
}