/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class Result11Builder {
    //the instance to build
    private Result11 result11;

    /**
     * Default constructor to initialize the instance
     */
    public Result11Builder() {
        result11 = new Result11();
    }

    public Result11Builder status(String status) {
        result11.setStatus(status);
        return this;
    }

    /**
     * an optional message
     */
    public Result11Builder message(String message) {
        result11.setMessage(message);
        return this;
    }

    /**
     * a unique identifier for the deleted Geo Location ; opaque but likely a GUID
     */
    public Result11Builder entryID(String entryID) {
        result11.setEntryID(entryID);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Result11 build() {
        return result11;
    }
}