/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class SearchResponseBuilder {
    //the instance to build
    private SearchResponse searchResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SearchResponseBuilder() {
        searchResponse = new SearchResponse();
    }

    public SearchResponseBuilder result(Result result) {
        searchResponse.setResult(result);
        return this;
    }

    public SearchResponseBuilder searchResult(SearchResult searchResult) {
        searchResponse.setSearchResult(searchResult);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SearchResponse build() {
        return searchResponse;
    }
}