/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class SearchResult 
        implements java.io.Serializable {
    private static final long serialVersionUID = -9168064163631336353L;
    private String inputIP;
    private List<IPAddressEntryPair> entries;
    /** GETTER
     * the input search string, with the proper '/' in CIDR, not '+' as needed in the endpoint URL
     */
    @JsonGetter("Input_IP")
    public String getInputIP ( ) { 
        return this.inputIP;
    }
    
    /** SETTER
     * the input search string, with the proper '/' in CIDR, not '+' as needed in the endpoint URL
     */
    @JsonSetter("Input_IP")
    public void setInputIP (String value) { 
        this.inputIP = value;
    }
 
    /** GETTER
     * matching IP Address and Object Entry IDs
     */
    @JsonGetter("Entries")
    public List<IPAddressEntryPair> getEntries ( ) { 
        return this.entries;
    }
    
    /** SETTER
     * matching IP Address and Object Entry IDs
     */
    @JsonSetter("Entries")
    public void setEntries (List<IPAddressEntryPair> value) { 
        this.entries = value;
    }
 
}
