/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class SearchResultBuilder {
    //the instance to build
    private SearchResult searchResult;

    /**
     * Default constructor to initialize the instance
     */
    public SearchResultBuilder() {
        searchResult = new SearchResult();
    }

    /**
     * the input search string, with the proper '/' in CIDR, not '+' as needed in the endpoint URL
     */
    public SearchResultBuilder inputIP(String inputIP) {
        searchResult.setInputIP(inputIP);
        return this;
    }

    /**
     * matching IP Address and Object Entry IDs
     */
    public SearchResultBuilder entries(List<IPAddressEntryPair> entries) {
        searchResult.setEntries(entries);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SearchResult build() {
        return searchResult;
    }
}