/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class SearchResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = -6893027190253801635L;
    private Result result;
    private SearchResult searchResult;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Result")
    public Result getResult ( ) { 
        return this.result;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Result")
    public void setResult (Result value) { 
        this.result = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("SearchResult")
    public SearchResult getSearchResult ( ) { 
        return this.searchResult;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("SearchResult")
    public void setSearchResult (SearchResult value) { 
        this.searchResult = value;
    }
 
}
