/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class TestForListMembershipResponseBuilder {
    //the instance to build
    private TestForListMembershipResponse testForListMembershipResponse;

    /**
     * Default constructor to initialize the instance
     */
    public TestForListMembershipResponseBuilder() {
        testForListMembershipResponse = new TestForListMembershipResponse();
    }

    public TestForListMembershipResponseBuilder result(Result24 result) {
        testForListMembershipResponse.setResult(result);
        return this;
    }

    /**
     * The IP address information referenced by Bouncer when building `ufw` rules
     */
    public TestForListMembershipResponseBuilder entry(IPAddress entry) {
        testForListMembershipResponse.setEntry(entry);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TestForListMembershipResponse build() {
        return testForListMembershipResponse;
    }
}