/*
 * BouncerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;

public class UpdateResponseBuilder {
    //the instance to build
    private UpdateResponse updateResponse;

    /**
     * Default constructor to initialize the instance
     */
    public UpdateResponseBuilder() {
        updateResponse = new UpdateResponse();
    }

    public UpdateResponseBuilder result(Result5 result) {
        updateResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public UpdateResponse build() {
        return updateResponse;
    }
}